apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: grafana-stack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: grafana-stack
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/created-by: kustomize
    app.kubernetes.io/usage: monitoring
    app.kubernetes.io/description: Namespace for Grafana monitoring stack
    